CREATE TABLE Users (
    Id SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(256) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    CreatedAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Groups (
    Id SERIAL PRIMARY KEY,
    GroupName VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Messages (
    Id SERIAL PRIMARY KEY,
    SenderId INT NOT NULL,
    GroupId INT NULL,
    Text TEXT NOT NULL,
    CreatedAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SenderId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (GroupId) REFERENCES Groups(Id) ON DELETE CASCADE
);

CREATE TABLE Files (
    Id SERIAL PRIMARY KEY,
    SenderId INT NOT NULL,
    FilePath VARCHAR(500) NOT NULL,
    GroupId INT NULL,
    CreatedAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SenderId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (GroupId) REFERENCES Groups(Id) ON DELETE CASCADE
);

CREATE TABLE GroupMembers (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL,
    GroupId INT NOT NULL,
    JoinedAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (GroupId) REFERENCES Groups(Id) ON DELETE CASCADE,
    CONSTRAINT unique_user_group UNIQUE (UserId, GroupId)
);
